### ISSUE TITLE
Zalatimo Bros

### ISSUE THREAD

**Issue by susalev** [susalev/restaurants#1]
@Alaa-Sawalmeh please write a review for Zalatimo Brothers.

**Comment by susalev** [comment]
@Bino-E do we have it in Waha circle?

**Comment by susalev** [comment]
@Alaa-Sawalmeh I see you added [a file](https://github.com/susalev/restaurants/blob/main/Zalatimo%20Brothers.md)

**Comment by Alaa-Sawalmeh** [comment]
yes
